language: python

python:
  - 3.6

#services: mariadb

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lapack-dev

install:
  - pip install -r requirements.txt

#before_script:
#  - mysql -e 'create database test;' -u root

script: 
  - python manage.py test

