version: "3"
services:

  web:
    build: ./
    volumes:
      - ./:/app
    ports:
      - 80:5000
    depends_on:
      - db
    links:
      - db:db
      - smtp:smtp
      - cache:cache

  db:
      image: mariadb:latest
      volumes:
        - ./db:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: rattler
          MYSQL_USER: rattler
          MYSQL_PASSWORD: 123456
      ports:
        - 3306:3306

  smtp:
      image: djfarrelly/maildev:latest
      ports:
        - 25:25
        - 8080:80

  cache:
      image: memcached:alpine
      ports:
        - "11211:11211"